### ISSUE TITLE
Side-Navigation (Command Index): No line breaks causing data overflow

### ISSUE THREAD

**Issue by ryunp** [Lexikos/AutoHotkey_L-Docs#100]
Some longer strings in the side navigation elements lack space characters causing overflow.

One of many [cases](http://ahkscript.org/docs/commands/Send.htm):
Mouse and Keyboard > Hotkeys and Hotstrings > Send/SendRaw/SendInput/SendPlay/SendEvent

![docs_sidebar_overflow](https://cloud.githubusercontent.com/assets/4276680/3873306/298ba55c-212e-11e4-8593-7970c1dccce1.gif)

Comma separated feels more elegant and technically saves a few bytes :+1::

![docs_sidebar_overflow](https://cloud.githubusercontent.com/assets/4276680/3873229/ca4a5d0a-212c-11e4-8ae2-43c434abbbe0.gif)

**Comment by Lexikos** [comment]
This was fixed a while ago by #101.
