### ISSUE TITLE
Why is the Function Object page named Functor.htm

### ISSUE THREAD

**Issue by TLMcode** [Lexikos/AutoHotkey_L-Docs#120]
Is there a reason why its named Functor?

**Comment by joedf** [comment]
A type of object???
http://en.wikipedia.org/wiki/Functor

**Comment by Lexikos** [comment]
Is there a reason for your question?

"Functor" is shorter than "FunctionObject" (or to be consistent, "Function"), and more departed from "Func", which is a different thing.  The term is also mentioned on the page itself.

> This is sometimes also referred to as a "functor".

**Comment by joedf** [comment]
**issue closed.** ?

**Comment by TLMcode** [comment]
Wanted to make sure it wasn't in error. Thanks for the clarification.

**Comment by Lexikos** [comment]
Sounds like a poorly designed "search" function. You can use [the index data](https://github.com/Lexikos/AutoHotkey_L-Docs/blob/master/docs/static/source/data_index.js) to find topics by name.
