### ISSUE TITLE
MPRESS / matcode.com is no longer

### ISSUE THREAD

**Issue by joedf** [Lexikos/AutoHotkey_L-Docs#133]
The line in question: [Scripts.htm#L146 (Permalink)](https://github.com/Lexikos/AutoHotkey_L-Docs/blob/47a053a2e50895fd0273d75032c99c0e2b25396f/docs/Scripts.htm#L146)
`http://www.matcode.com/mpress.htm` is no longer online. MPRESS is under a pseudo-MIT license. That said, I have uploaded an archived version of the webpage with a copy of the download here:   
**Archived files:** https://autohotkey.com/mpress/
**Archived webpage:** https://autohotkey.com/mpress/mpress_web.htm

**Comment by Lexikos** [comment]
See 9e86d353.

I left the official link for now, as it being offline might not be intentional/permanent.

**Comment by joedf** [comment]
I see... Understood.
