### ISSUE TITLE
NumLock missing from Key List page

### ISSUE THREAD

**Issue by G33kDude** [Lexikos/AutoHotkey_L-Docs#136]
It appears that actual NumLock key is missing from the [key list page](https://github.com/Lexikos/AutoHotkey_L-Docs/blob/master/docs/KeyList.htm). I'm not sure where it should go, maybe at the top of the numpad keys?

**Comment by Lexikos** [comment]
Thanks for pointing it out.  I've taken the opportunity to clarify the Numpad section (in commit 5788148).
