### ISSUE TITLE
'Up' hotkeys

### ISSUE THREAD

**Issue by mmikeww** [Lexikos/AutoHotkey_L-Docs#166]
Do 'Up' hotkeys use the keyboard hook? 

I ask because it doesn't look like the `Send` command triggers them:

```autohotkey
var := 0
a up::
   var++
   tooltip, % "var=" var
   if (var > 0)
      Send, {a up}
return
```

That hotkey does not recursively trigger itself. However, if you change both the Definition and the Send command to both use `a` instead of `a up`, then the hotkey does trigger itself.

If 'Up' hotkeys do use the hook, I think that note should be added to the docs in the 'Up' block:

https://autohotkey.com/docs/Hotkeys.htm

And if so, does that mean a corresponding normal/down hotkey also uses the hook if it were defined in the same script?

**Comment by Lexikos** [comment]
I don't think it's necessary to list all of the conditions for whether a hotkey uses the hook. Automation is often a case of trial and error, and it's immediately obvious that Send doesn't trigger the hotkey. Aside from that, you need only use `ListHotkeys` to see what type of hotkey it is, without having to remember all of the conditions and apply them correctly.

There's a simplified list already:

> The $ prefix has no effect for mouse hotkeys, since they always use the mouse hook. It also has no effect for hotkeys which already require the keyboard hook, including any keyboard hotkeys with the tilde (~) or wildcard (*) modifiers, key-up hotkeys and custom combinations.

**Comment by mmikeww** [comment]
> I don't think it's necessary to list all of the conditions for whether a hotkey uses the hook. 

Of course its not necessary, but I don't see how its a bad thing when it costs so little to add a line to the docs. But again, we seem to differ: you seem to prefer concise docs and I prefer verbose.

> Aside from that, you need only use `ListHotkeys` to see what type of hotkey it is

Did not know this, thanks

**Comment by Lexikos** [comment]
> ...  I don't see how its a bad thing when it costs so little to add a line to the docs.

I wasn't talking about just this case.

Here's the thing: to document a list of all the conditions for whether a hotkey uses the hook, one needs to first *understand* all the conditions. I don't. The hotkey code is very complex, a bit repetitive, and not fun to read. And any such list would not offer complete information anyway. For instance, one of the conditions is that if RegisterHotkey fails, the hook will be used. Putting aside the unknowable (which hotkeys other applications have already registered), there may be some hotkeys which the OS never allows to be registered, but aren't documented anywhere.

Anyway, I've skimmed over the code and added notes for a few of the clear-cut cases in 07dc918d.
