### ISSUE TITLE
Add "Improve this page on GitHub" button

### ISSUE THREAD

**Issue by Stevoisiak** [Lexikos/AutoHotkey_L-Docs#192]
One of my favorite features of [Travis CI's online documentation](https://docs.travis-ci.com/user/getting-started/) is a small button on every page that allows readers to easily suggest improvements to the current page on GitHub.

[![Improve this page on GitHub](https://user-images.githubusercontent.com/1330770/29535157-df8d5042-8686-11e7-942b-2e90b24c296b.png)](https://github.com/travis-ci/docs-travis-ci-com/edit/master/user/getting-started.md)

I would like to suggest a similar button be added to the documentation for AutoHotkey.

![untitled](https://user-images.githubusercontent.com/1330770/29535814-5a1cefbe-8689-11e7-8af2-65ebef29ce26.png)

I believe that adding a "edit on GitHub" button would make the process of contributing to AHK much simpler for new potential contributors.

**Comment by Lexikos** [comment]
You can add it if you like.

**Comment by Ragnar-F** [comment]
I've added a button for editing the current page on GitHub into the new sidebar.

**Comment by Grass-H0PEr** [comment]
I didn't even know the AHK docs were hosted on GitHub until today.

Fantastic addition.

**Comment by Lexikos** [comment]
@Grass-H0PEr The docs are not hosted on GitHub.

#185 has been merged; however, the script which pulls the content across to autohotkey.com appears to be not working at the moment.

**Comment by Lexikos** [comment]
The current documentation at autohotkey.com has the "edit on GitHub" button (looks like a pen/pencil).
