### ISSUE TITLE
Docs are broken in Firefox with some addons

### ISSUE THREAD

**Issue by fabsenet** [Lexikos/AutoHotkey_L-Docs#210]
Hi,

your docs page looks very broken to me in firefox:
![image](https://user-images.githubusercontent.com/2065705/33380800-8cdc64ac-d51c-11e7-82f1-a0bd98611917.png)

I traced the issue down to this code line:

https://github.com/Lexikos/AutoHotkey_L-Docs/blob/788afdd15ba0161270c01b7f09e8640efbf0b0a9/docs/static/content.js#L42

If I execute `document.scripts` in the firefox debugger, i get this result listing:

```text
document.scripts
[…]
0: <script id="custom-useragent-string" type="text/javascript">
1: <script src="static/content.js" type="text/javascript">
2: <script type="text/javascript" src="/source/data_translate.js">
3: <script type="text/javascript" src="/source/data_toc.js">
4: <script type="text/javascript" src="/source/data_index.js">
5: <script type="text/javascript" src="/source/data_search.js">
"custom-useragent-string": <script id="custom-useragent-string" type="text/javascript">
```

The extension in question is [custom-useragent-string](https://addons.mozilla.org/en-US/firefox/addon/custom-useragent-string/) but I guess there might be other extensions which would break your script code:

```js
var scriptDir = document.scripts[0].src.substr(0, document.scripts[0].src.lastIndexOf('/'));
```

I think a fix might be easily possible but I do not have the picture, why you are using this approach and why you need scriptDir at all.

**Comment by Ragnar-F** [comment]
Pull request #209 contains a fix for this issue.

**Comment by fabsenet** [comment]
tested the changed script in my firefox and it would work! nice!

You can deploy it 😃  👍

**Comment by joedf** [comment]
@Lexikos Close issue.
