### ISSUE TITLE
ErrorLevel as a parameter name causing error

### ISSUE THREAD

**Issue by Ragnar-F** [Lexikos/AutoHotkey_L-Docs#233]
https://github.com/Lexikos/AutoHotkey_L-Docs/blob/c56ee890a2d77473945db31f7e00d9bf7d38a74a/docs/commands/Gui.htm#L286

**just me** has found out that `ErrorLevel:=""` causes the error "Illegal parameter name".

Should this be changed in the docs, or does the AutoHotkey code need to be modified to make it work this way? Actually, there's nothing wrong with using ErrorLevel as a parameter name.

**Comment by Lexikos** [comment]
Nothing wrong with using ErrorLevel as a parameter name? It is *illegal*.

> Built-in variables such as Clipboard, ErrorLevel, and A_TimeIdle are never local (they can be accessed from anywhere), and cannot be redeclared.

If you redeclared it as local (or as a parameter, which is the same thing), the function would not be able to check the actual ErrorLevel. Someone may expect commands to affect the local ErrorLevel, but it wouldn't work that way.

The documentation is intended to show that the fourth parameter receives the same value as ErrorLevel. In actual code, you should use a *meaningful* name.  The meaning depends on the control or the script.

You may modify it if you wish.
