### ISSUE TITLE
KeyWait page

### ISSUE THREAD

**Issue by john-cj** [Lexikos/AutoHotkey_L-Docs#241]
I'm not professional AHK programmer, but from my point of view, at least one example in KeyWait page is misleading, because:

> Yeah, I've heard of this mistake being made before... perhaps the docs need to have a note in there about how it waits for the key to be in the up state, rather than an up action. - camerb (moderator)
>
> _https://autohotkey.com/board/topic/66488-keywait-not-waiting/_

Here is current example from docs:

``` ahk
~CapsLock::
  KeyWait, CapsLock ; Wait for user to physically release it.
  MsgBox You pressed and released the CapsLock key.
return
```

In the example above, we could use **any** key in the KeyWait line, and it will not change anything. Here it is:

``` ahk
; Press CapsLock and you will see message box, despite you have "keywait, z"
~CapsLock::
  KeyWait, z ; Wait for user to physically release it.
  MsgBox You pressed and released the CapsLock key.
return
```

And here is my own example. From my point of view, it's correct and not misleading:

``` ahk
keyWait, lButton, d
keyWait, lButton
soundBeep, 300, 300
return
```

I don't sure, though.

**Comment by Ragnar-F** [comment]
You are using the example in the wrong way. KeyWait causes the message box to be displayed only when you release CapsLock. Without KeyWait, the message box is already displayed when you press CapsLock down.

This prevents CapsLock from auto-repeating and is basically synonymous with:
```autohotkey
~CapsLock up::
  MsgBox You pressed and released the CapsLock key.
return
```
