### ISSUE TITLE
Endless refresh loop on Windows

### ISSUE THREAD

**Issue by Fastigium** [Lexikos/AutoHotkey_L-Docs#251]
I'm posting this for my dad who doesn't have a GitHub account:

> Dear Autohotkey,
> 
> The documentation page of autohotkey.com can not be loaded on a Windows machine. It gives trouble on IE, FF and Chrome. On any other platform Android, Linux, MacOS, the site loads normal[ly].

He showed me the problem: when he goes to autohotkey.com on a Windows laptop and clicks the Documentation link on top, the resulting page just keeps refreshing endlessly. He said the problem also occurred on the Windows computer he has at work. I hope you'll be able to reproduce the problem; let me know if you can't.

**Comment by joedf** [comment]
Please clear your browser's cache and cookies.
The issue has been reported here: https://autohotkey.com/boards/viewtopic.php?f=3&t=46252

**Comment by Ragnar-F** [comment]
Usually it helps to press CTRL+F5 in your browser to refresh the cache, and then open the help in a new tab. Sooner or later, the cache will be automatically refreshed, but this may take days.

**Comment by Fastigium** [comment]
That seems to have done the trick! Feel free to close this issue, or leave it open for a few days in case anyone else runs into this problem and looks for an open issue here. Thank you both!

**Comment by joedf** [comment]
Close issue?
