### ISSUE TITLE
Propose New Logo

### ISSUE THREAD

**Issue by anaufalm** [Lexikos/AutoHotkey_L-Docs#281]
Hello, Im graphic designer. I want to submit new logo for your project: **AutoHotkey_L**, I've see your master [repo](https://github.com/Lexikos/AutoHotkey_L) and didn't see Issues tab, so I come here.

May I? Dont think about anything, this is free. :)

**Comment by derz00** [comment]
Share it so we can see what you have ! 👍

**Comment by joedf** [comment]
Interesting concept... but where does this come from? only the L is represented? It looks like an electronic circuit :]

**Comment by anaufalm** [comment]
I just focus on macro. Would it be nice to create a hotkey? I'll make another design

**Comment by pattagobi** [comment]
can I participate too in this, please?

**Comment by joedf** [comment]
There's no stopping anyone, but there's no guarantee that the logo will be used. If the staff, community and ultimately lexikos or chris like the logo. I don't see why not. However, I do suggest that it may be important to stay true to the original idea of ahk: keyboards, script, automation, etc.

**Comment by Lexikos** [comment]
It's not bad, but I'm not looking to re-brand. (I'm a *bit* late, I know.)
