### ISSUE TITLE
Is there a way to disable highlighting the searched word?

### ISSUE THREAD

**Issue by schittli** [Lexikos/AutoHotkey_L-Docs#283]
Good evening

We usually do not search for a specific string which should be highlighted,
but for an AutoHotkey command man page.
Therefore, we just search for e.g. `clip` and then to click on `Clipboard`.

Then, the result is very annoying: it feels like every 3rd word is partially highlighted which massively reduces the readability.

Therefore, we always manually delete the search word and reload the page, so that it looks and reads perfectly.

**Therefore the question: is there a way to search for AutoHotkey commands without having everything highlighted in the result?**

### Thanks a lot for this great piece of software!
It's very hard to write scripts because of the non-intuitive syntax for the variable handling,
but after spending much time for try and error, the result is always great and gives amazing feedbacks :-)

**Comment by derz00** [comment]
Yes there is way. Use the "Index" tab, and type for the command/keyword/etc that you want to find.

![image](https://user-images.githubusercontent.com/30033758/40207206-60e89414-5a01-11e8-956c-44c343e4017e.png)

**Comment by Lexikos** [comment]
Perhaps @Ragnar-F can add a setting to disable the highlighting.

**Comment by Ragnar-F** [comment]
I've added a checkbox under the selection list of the search tab to enable the word highlighting and jump to the first match. The word highlighting is now disabled by default.

**Comment by schittli** [comment]
Good afternoon,
… I just had some free days, could finally read my e-mails - and wow!, 
**thank you very much for the great support!**
