### ISSUE TITLE
Wrong link on download page

### ISSUE THREAD

**Issue by joedf** [Lexikos/AutoHotkey_L-Docs#295]
On the download page
https://autohotkey.com/download/

The link for the installer "extract to" link is
https://autohotkey.com/docs/Scripts.htm#install

but it should now be
https://autohotkey.com/docs/Program.htm#install

**Comment by Ragnar-F** [comment]
Nothing I can do here, since it's not part of the docs repo. I thought you had access to the server files - why don't you change it yourself?

**Comment by joedf** [comment]
You are correct, but Lexikos is the one that manages the main download page possibly through a script. If I manually fix now, it simply be overwritten by the next release.
I have change it for now.

**Comment by Lexikos** [comment]
I have fixed my local copy used by the release script.
