### ISSUE TITLE
Search > WinSet v2 Broken Links

### ISSUE THREAD

**Issue by egocarib** [Lexikos/AutoHotkey_L-Docs#301]
If you search for "WinSet" or "WinGet" in the [v2 docs](https://lexikos.github.io/v2/docs/), many of the links that appear in the search pane are broken and take you to an error page. This is because they are still pointing to WinSet.htm and WinGet.htm which no longer exist.

**Comment by Lexikos** [comment]
That is merely because the search index has not been rebuilt, since that is done by the release script and there have been no v2 releases since Ragnar split WinSet.htm into separate files.
