### ISSUE TITLE
View Menu

### ISSUE THREAD

**Issue by ursi** [Lexikos/AutoHotkey_L-Docs#320]
View -> Content, Index, Search, (and Favorites?) all cannot be manually selected.

**Comment by Ragnar-F** [comment]
This is because these menu items apply to the built-in (old) sidebar, which is disabled. Our CHM file uses a JavaScript-based sidebar. There is no way to reuse or disable these menu items.

**Comment by Ursi** [comment]
Why not just get rid of them then?

**Comment by Ragnar-F** [comment]
They can't be removed.
