### ISSUE TITLE
Error in Docs/Code

### ISSUE THREAD

**Issue by liar666** [Lexikos/AutoHotkey_L-Docs#327]
Hi,

At the end of documentation page:
https://autohotkey.com/docs/commands/SetNumScrollCapsLockState.htm
It is written:
"Remarks
A key can also be toggled to its opposite state via the Send command; for example: Send {CapsLock}."

This does not work with AHK v 1.30.0.0.

The following file swaps LCtrl with CapsLock and tries to circumvent Windows' dirty hardcoded mapping of AltGr to LControl+RAlt.

As the code does not behave similarly with Send {CapsLock} or with manual toggling of CapsLock status, there's a bug either in the code or the documentation...

```
#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.

CalledFromRWin := 0

; Disable AltGr
LControl & RAlt::

; Simulate AltGr on RWin
RWin::
  CalledFromRWin := 1
  Send, {LControl down}{RAlt down}
  Sleep 500
  Send, {RAlt up}{LControl up}
  CalledFromRWin := 0
  Return
  
; Swap LCtrl & CapsLock
CapsLock::LCtrl
LControl::
  ;MsgBox, "%CalledFromRWin%"
  If (CalledFromRWin == 0) {
	Send {CapsLock}  ;;;; <--- using this DOES NOT work, but following lines DO!
	;if GetKeyState("CapsLock", "T") = 1 {
	;	SetCapsLockState, off
	;} else if GetKeyState("CapsLock", "T") = 0 {
	;	SetCapsLockState, on
	;}
  }
  Return
 ```

**Comment by Ragnar-F** [comment]
Note that `LControl & RAlt::` should be `LControl & RAlt::return` to disable AltGr, otherwise it would perform the same action as the RWin below (if not intended to do so).

I've found the following note in commands/Send.htm, which works:

> CapsLock (using SetCapsLockState is more reliable on Win 2k/XP). **Sending {CapsLock} might require SetStoreCapsLockMode Off beforehand.**

I'll add this note to the note you mentioned.

By the way, in AHK v1.1.30+, you can also use the following to toggle CapsLock:

```autohotkey
SetCapsLockState % !GetKeyState("CapsLock", "T")
```
