### ISSUE TITLE
v2: BlockInput - undefined variables ON and OFF

### ISSUE THREAD

**Issue by hoppfrosch** [Lexikos/AutoHotkey_L-Docs#334]
**AHK-V2 Documentation**

Command: **BlockInput** (page: commands\BlockInput.html)

### Current documentation: 
> Mode
>  1: One of the following words:
> On or 1 (true): The user is prevented from interacting with the computer (mouse and keyboard input has no effect).
> Off or 0 (false): Input is re-enabled.

### Issue

Neither **On** nor **Off** are defined within AHK V2  (or at least they are not accessible within BlockInput)

### Solution:

Just use:
> Mode
>  1: One of the following words:
> True (1): The user is prevented from interacting with the computer (mouse and keyboard input has no effect).
> False (0): Input is re-enabled.

**Comment by Ragnar-F** [comment]
It works with `BlockInput "On"` etc. I guess you tried `BlockInput On` etc.

In AHK v2, strings must be enclosed in quotation marks (except for directives and some control flow statements).

**Comment by hoppfrosch** [comment]
Yes - thats it. 

As `True` an `False` work without quotation marks, I didn't get this correctly from the documentation - maybe caused by not being a native english speaker (should have a look in your german docu :-)

Maybe changing the example to `Blockinput "Off"` from `Blockinput False` might show the usage
