### ISSUE TITLE
If (Expression)

### ISSUE THREAD

**Issue by JulesverneOnGitHub** [Lexikos/AutoHotkey_L-Docs#335]
Suggestion:  Including a remark that If (Expression) is case insensitive.  To make it case sensitive see [StringCaseSense](https://github.com/Lexikos/AutoHotkey_L-Docs/issues/335)

Thanks! Jules

**Comment by Ragnar-F** [comment]
That's true for legacy-if (commands/IfEqual.htm), but not entirely for expression-if (commands/IfExpression.htm). For example, `if ("a" == "A")` is always case-sensitive and `if ("a" = "A")` is always case-insensitive. StringCaseSense On/Off does not affect such statements.

There are multiple links to the expression section, which also covers the relevant operators (namely comparison operators such as > or ==) including their case sensitivity behavior. I think that's enough.

**Comment by Lexikos** [comment]
*If (expression)* does not perform string comparisons; it merely evaluates the *truth* of its argument and jumps execution either to or over its body. Any string comparison performed within the expression occurs before the command itself executes, just the same as when you use an expression in the parameter list of any other command.

For instance, in `MsgBox % a = b`, MsgBox is neither case sensitive nor case insensitive, but the `=` operator is case insensitive.
