### ISSUE TITLE
[docs] optional parameters

### ISSUE THREAD

**Issue by duianto** [Lexikos/AutoHotkey_L-Docs#343]
There are two optional parameter sections `[]` in the definition (yellow box) for these two commands:
https://lexikos.github.io/v2/docs/commands/NumGet.htm
https://lexikos.github.io/v2/docs/commands/NumPut.htm

Maybe they should be combined into a single optional section for both parameters.

And only the second of three parameters is marked as optional for this command:
https://lexikos.github.io/v2/docs/commands/ComObjQuery.htm

It seems strange that only a middle parameter is optional. The closing square bracket should probably be moved to the right of the last parameter. Because the second sentence for the third parameter `SID` says:
>When omitting this parameter, also omit the comma.

which indicates that the third parameter also is optional.

**Comment by Ragnar-F** [comment]
This was done on purpose. Read the remarks.

NumGet: If only two parameters are present, the second parameter can be either _Offset_ or _Type_...
NumPut: If only three parameters are present, the third parameter can be either _Offset_ or _Type_...

ComObjQuery: Yes, it is strange, but not wrong. You can either write `ComObjQuery(ComObject, SID, IID)` or `ComObjQuery(ComObject, IID)`. If the closing square bracket would be moved to the right side of the last parameter, this would imply `ComObjQuery(ComObject)` which is wrong of course.
