### ISSUE TITLE
Type - missing at least the return value of "Func"

### ISSUE THREAD

**Issue by kczx3** [Lexikos/AutoHotkey_L-Docs#355]
Not sure if others are missing as well, but the Type function will return "Func" for func objects.

**Comment by Lexikos** [comment]
> If Value is an object, the return value is the object's class name.

The documentation for Type does not list class names. There is a virtually infinite set of values that it could return. I would prefer not to list the built-in classes on that page, though Func might be important enough to mention. The name of each built-in class could be clarified in the documentation for that class.
