### ISSUE TITLE
Finding Special Keys

### ISSUE THREAD

**Issue by Hikarizu-42** [Lexikos/AutoHotkey_L-Docs#372]
https://lexikos.github.io/v2/docs/KeyList.htm#SpecialKeys
Documentation says that you can find a mouse/keyboard key with the following method, but the method only lists KeyboardHook and not MouseHook. I know it's a small thing and even when knowing basically nothing about AHK I managed to stumble into it relatively quickly, it would be nice if MouseHook is mentioned there as well.

**Comment by Ragnar-F** [comment]
I'm not sure if #InstallMouseHook can detect unknown mouse buttons. Did you find the button you were looking for by using #InstallMouseHook in combination with KeyHistory?

**Comment by Lexikos** [comment]
The way the mouse works in Windows does not have the provision for any buttons other than those which are predefined. Mice with more than the standard buttons work by effectively being both a mouse and a generic USB HID (the latter being handled by additional manufacturer-specific software).

So in other words, the mouse hook will not allow you to discover or detect any buttons beyond those already listed in the documentation.
