### ISSUE TITLE
Block comments - Missing detail

### ISSUE THREAD

**Issue by joedf** [Lexikos/AutoHotkey_L-Docs#398]
The documentation specifies:
> the `/*` and `*/` symbols can be used to comment out an entire section, but only if the symbols appear at the beginning of a line.

Source: https://www.autohotkey.com/docs/Language.htm#comments

However, block comments are still valid if indented such as:
```ahk
#Warn
MsgBox 1

	/*
	 * indented comment line 1
	   MsgBox Comment
	 * indented comment line 3
	 */

MsgBox 2
```
Running the above test script executes with no warnings or errors, and shows only two message boxes (1,2). Maybe mention spaces and tabs instead of just "beginning of a line"?

**Comment by robertcollier4** [comment]
My recommendation to change it to:

    the /* and */ symbols can be used to comment out an entire section, but only if the symbols appear at the beginning of a line (excluding whitespace).

This affected writing a lexer for one of our tmLanguage Sublime librarys.
