### ISSUE TITLE
Is ComObjParameter a part of AutoHotkey core?

### ISSUE THREAD

**Issue by usernamehw** [Lexikos/AutoHotkey_L-Docs#414]
I'm trying to edit outdated snippets for ahk extension support and never even used ComObj. There's an old snippet included `ComObjParameter(${1:VarType}, ${2:Value} [, ${3:Flags}])` so I would like to know if it's present in the language (as of 1.1.32.00).

**Comment by Ragnar-F** [comment]
It is still functional in v1 and will remain so, but it is deprecated. Use ComObject() instead.

https://www.autohotkey.com/docs/commands/ComObjActive.htm states the following:

> In current versions, any function-call beginning with "ComObj" that does not match one of the other COM functions actually calls ComObjActive. For example, ComObjEnwrap(DispPtr) and ComObjActive(DispPtr) are both equivalent to ComObject(DispPtr) (VarType 9 is implied). However, this behaviour will be unavailable in a future release, so it is best to use only ComObject() and ComObjActive() as shown on this page.

**Comment by usernamehw** [comment]
Thanks.
