### ISSUE TITLE
Website 404

### ISSUE THREAD

**Issue by bace1996** [Lexikos/AutoHotkey_L-Docs#420]
sorry for send this not-programing issue, but i just dont know where should I go.
https://www.autohotkey.com/docs/AutoHotkey.htm
the url above are returning 404 error, witch i guess it may be the offcial site of this repo

**Comment by joedf** [comment]
@bace1996 I am not getting a 404. The page loads correctly for me. Can you load any of the other documentation pages?

**Comment by bace1996** [comment]
I can normally access other websites but this doc site.
I tried follow url but all same 404 error
https://www.autohotkey.com/docs/FAQ.htm

**Comment by joedf** [comment]
What browser are you using? Are you blocking javascript? Could you try with a VPN?
Otherwise the documentation is also available as a download, packaged with AutoHotkey.
https://www.autohotkey.com/download

**Comment by bace1996** [comment]
infact i tried with several different proxy but not work, but i can download this, thx
