### ISSUE TITLE
old syntax   “is”

### ISSUE THREAD

**Issue by wyagd001** [Lexikos/AutoHotkey_L-Docs#440]
v2/docs/Objects.htm#primitive
use old syntax   “n is 'number'”
1. By contrast, n is 'number' is true if n is a number or a numeric string.
2. The is operator can be used with these classes. For example, n is Number is equivalent to n.HasBase(Number.Prototype)

**Comment by Ragnar-F** [comment]
The second one does not need to be fixed. It is still valid and refers to the code above it. See the [is operator](https://lexikos.github.io/v2/docs/Variables.htm#is).
