### ISSUE TITLE
Vectorized Logo

### ISSUE THREAD

**Issue by joedf** [Lexikos/AutoHotkey_L-Docs#446]
I don't consider this crucial, but I think this will be more relevant as display technologies become clearer and more sophisticated or advanced. The logo is looking blurry on newer screens. I've tried recreating (with Inkscape) the "modern" logo (not sure who the original "concept art" creator of this is, let me know if you do). It's not perfect; it will never be 100% accurate because I don't have anything other than the raster image. Particularly the key shapes and shadowing/shading are slightly different, but I think this is good enough. I'd like a second opinion... If this is good enough, I am considering exporting higher resolutions PNGs for autohotkey.com too.

**TLDR:** Perhaps, we'll want to consider using a "vectorized" image for the logo instead or at least a higher resolution one.

**Thoughts?**

Original PNG format:
![original](https://www.autohotkey.com/docs/static/ahk_logo.png)

Recreated in SVG format:
![full logo](https://upload.wikimedia.org/wikipedia/commons/5/5a/Modern_AutoHotkey_Logo_%28full%29.svg)
https://commons.wikimedia.org/wiki/File:Modern_AutoHotkey_Logo_(full).svg

![logo no-text](https://upload.wikimedia.org/wikipedia/commons/5/5e/Modern_AutoHotkey_Logo_%28no_text%29.svg)
https://commons.wikimedia.org/wiki/File:Modern_AutoHotkey_Logo_(no_text).svg

Single key example:
<img width="72" alt="ahk_logo-one_key" src="https://user-images.githubusercontent.com/3848219/88973033-7f364300-d284-11ea-9050-b31d047cb836.png">

Also available in SVG, everything's in here:
[ahk_logo-svg.zip](https://github.com/Lexikos/AutoHotkey_L-Docs/files/5003733/ahk_logo-svg.zip)

**Comment by Ragnar-F** [comment]
Well done. However, I see two issues, but the first one is solvable and the other one is reasonable nowadays:

- SVG does not work on IE8 (IE8 support is still relevant for the v1 docs). Working fallback method for the logo in AutoHotkey.htm:
```html
<img src="static/ahk_logo.svg" onerror="this.src='static/ahk_logo.png'; this.onerror=null;" alt="AutoHotkey">
```
- Size (6.6 KB vs 58.3 KB)

So I don't mind if this is included in the docs (and generally in autohotkey.com, where the above issues are irrelevant anyway).

**Comment by joedf** [comment]
Oh yeah, I keep forgetting about IE8... 😬
Also, neat! I've never thought of using `onerror` like that, and I believe the `null` stops it from an infinite loop if it fails too, correct? I think a fallback is a great idea.

Either way, even just using a higher resolution PNG I think is good too.

As for size, I ran it through this [optimizer](https://jakearchibald.github.io/svgomg/) (removes any metadata, editor info, uglifies it, etc.): 
[ahk_logo-optimize.zip](https://github.com/Lexikos/AutoHotkey_L-Docs/files/5007334/ahk_logo-optimize.zip)
This way, it's 19 KB instead of 58 KB while still being visually the same.

**Comment by Ragnar-F** [comment]
> I believe the null stops it from an infinite loop if it fails too, correct?

That's correct. However, I didn't make it up. This method is one of many.

> Either way, even just using a higher resolution PNG I think is good too.

With the optimization, there should be nothing to stop us from using SVG.

**Comment by Lexikos** [comment]
I have no objections.

**Comment by Ragnar-F** [comment]
I have taken the initiative and added the SVG, but I used another optimizer (svgminify.com) because there is indeed a loss of quality; specifically, the font looks blurry at lower resolutions. The SVG file is slightly larger now (26 KB), but I think that's acceptable.

**Comment by joedf** [comment]
Looks good 👍 
I will use this newer SVG file for parts of autohotkey.com
