### ISSUE TITLE
#If WinActive goes a error in v2

### ISSUE THREAD

**Issue by yunlongYoung** [Lexikos/AutoHotkey_L-Docs#457]
when I try the example on https://lexikos.github.io/v2/docs/Tutorial.htm#s22, it turn to a error.

```
#If WinActive("Untitled - Notepad")
#Space::MsgBox "You pressed WIN+SPACE in Notepad."
```

![image](https://user-images.githubusercontent.com/10031057/99775204-e173c600-2b49-11eb-8eef-375bf461fe75.png)

Does v2 support this code?

**Comment by yunlongYoung** [comment]
and, https://lexikos.github.io/v2/docs/Tutorial.htm#s71

this went wrong, can not init the object like this.
`Banana := {"Color": "Yellow", "Taste": "Delicious", "Price": 3}`

![image](https://user-images.githubusercontent.com/10031057/99780270-36670a80-2b51-11eb-9a3b-5417f3541b4d.png)

**Comment by Ragnar-F** [comment]
The tutorial has not yet been fully updated to reflect the latest v2 changes. For the first case, use the following:

```autohotkey
#HotIf WinActive("Untitled - Notepad")
#Space::MsgBox "You pressed WIN+SPACE in Notepad."
```

For the second case, use the following:
```autohotkey
Banana := Map("Color", "Yellow", "Taste", "Delicious", "Price", 3)
```

For more details, see [#HotIf](https://lexikos.github.io/v2/docs/commands/_HotIf.htm) or [Objects](https://lexikos.github.io/v2/docs/Objects.htm).

**Comment by Lexikos** [comment]
It appears this issue was fixed.
