### ISSUE TITLE
Request to replace Script Showcase's On-Screen Keyboard with its third-time successor

### ISSUE THREAD

**Issue by KeronCyst** [Lexikos/AutoHotkey_L-Docs#459]
To Joe DF: oops, I didn't realize that Script Showcase suggestions should be filed as "issues" here!

I saw that the Script Showcase's On-Screen Keyboard had some busted functionality (some keys weren't working) and was missing many keys for its ANSI layout.

I partnered with /u/anonymous1184 on Reddit to fix those keys and build upon a key-flashing successor with more capabilities.

I would like to request for the Script Showcase's On-Screen Keyboard to be replaced by the On-Screen ANSI Keyboard: https://gist.github.com/KeronCyst/d6e4468273a823794ca2e686e29ba28a

A demo GIF of the new keyboard is in the comments right under that code on that same page.

I think this could help a lot of people! ☺

**Comment by joedf** [comment]
I mainly suggested this, since the script showcase is part the documentation. 👍

**Comment by KeronCyst** [comment]
Okay, I put it here now if that may make it seem more official: https://github.com/KeronCyst/OSAK

This is my first-ever repo so I have no idea of what I'm doing, lol.

**Comment by joedf** [comment]
Looks good 😉👍

**Comment by Lexikos** [comment]
If this was a PR, I would merge it.

**Comment by KeronCyst** [comment]
Sorry, this would be my first time ever doing a PR so I'm not sure! Is this right; just drop the code in here? https://github.com/Lexikos/AutoHotkey_L-Docs/compare/master...v2

**Comment by joedf** [comment]
> 
> 
> Sorry, this would be my first time ever doing a PR so I'm not sure! Is this right; just drop the code in here? [master...v2](https://github.com/Lexikos/AutoHotkey_L-Docs/compare/master...v2)

I believe just **master**, unless you've made a v2 version of the script. Just click the link I have here for you to produce a fork/edit directly from GitHub.
**master (v1):** https://github.com/Lexikos/AutoHotkey_L-Docs/edit/master/docs/scripts/KeyboardOnScreen.ahk

In case you want to update the **v2** version: https://github.com/Lexikos/AutoHotkey_L-Docs/edit/v2/docs/scripts/KeyboardOnScreen.ahk

You'll likely need to do a second PR if you want to make for **v2** also. You can also reference this issue using "#459".

**Comment by KeronCyst** [comment]
Hmm, didn't even think of that; just v1 for now! Hmm… I _think_ I did it correctly… forked and then PR'd…
