### ISSUE TITLE
Suggestion: make tenkeyless version of  KeyboardOnScreen.ahk

### ISSUE THREAD

**Issue by hammadsheikh** [Lexikos/AutoHotkey_L-Docs#543]
Tenkeyless keyboards have become popular in the gaming community. It would be good if there was an onboard keyboard with tenkeyless layout. I am imagine three ways to accomplish this:

- create a try menu item that can hide the numpad
- introduce an option within the script (e.g., "k_TenKeyLess = y") that changes the layout
- create a new ahk file, specifically for tenkeyless keyboards (I already created one for myself)

Let me know if I can help with this issue and which route you think is the best.

**Comment by Ragnar-F** [comment]
For such things, the forum is the better choice. The docs are not a place to store scripts. The current scripts are sufficient to get a good impression of what AutoHotkey is capable of.

**Comment by hammadsheikh** [comment]
This makes sense. I spent some time yesterday to implement the TenKeyLess as an option in the script. Will share it on the forum.

**Comment by Lexikos** [comment]
A what?

Ohhh... a numpad. I wouldn't go without one, but mine is separate to the rest of the keyboard.
