### ISSUE TITLE
HotKey Brightness up - Brightness Down - HP Pavillion 600 keyboard

### ISSUE THREAD

**Issue by SvenLenR** [Lexikos/AutoHotkey_L-Docs#566]
For my HP Pavillion 600 keyboard, i'm looking for the hotkeys of Brightness up and Brightness down.
Because the keyboard don't have a FN lock, we use the next script, but without a change of F7 and F8.
The current script:
; F1 | Mute 
VOLUME_MUTE::F1
F1::VOLUME_MUTE

; F2 | Volume Down 
VOLUME_DOWN::F2
F2::VOLUME_DOWN

; F3 | Volume Up
VOLUME_UP::F3
F3::VOLUME_UP

; F4 | Last Song
MEDIA_PREV::F4
F4::MEDIA_PREV

; F5 | Play/Pause
MEDIA_PLAY_PAUSE::F5
F5::MEDIA_PLAY_PAUSE

; F6 | Next song
MEDIA_NEXT::F6
F6::MEDIA_NEXT

; F7 | Brightness Down

; F8 | Brightness Up

; F9 | Search
BROWSER_SEARCH::F9
F9::BROWSER_SEARCH

; F10 | Toggle display mode for multi-screen
<#Tab::
SendInput {F10}
Return
				
; F11 | ???
<^<#F21::
SendInput {F11}
Return

; F12 | System Settings
<#F21::
SendInput {F12}
Return

**Comment by Lexikos** [comment]
This is the issue tracker for the AutoHotkey documentation. You have not reported an issue, requested a change, or even asked a question. I can infer what you want from your comments, but it is outside the scope of this issue tracker. I suggest you post on the forums.
