### ISSUE TITLE
Some potential search terms for data_index.js

### ISSUE THREAD

**Issue by Animan8000** [Lexikos/AutoHotkey_L-Docs#569]
Some search terms for [data_index.js](https://github.com/Lexikos/AutoHotkey_L-Docs/blob/master/docs/static/source/data_index.js) I had in mind:
- `Linefeed`
- `Line feed`
- `New line`
- `Tab`

Though, I don't recall where exactly in the documentation they were explained in depth and how they look like. The reason for these search terms is to figure quickly out how they look like in AHK syntax, in case the user forgot it or just wants to know it asap.

**EDIT:** I had three extra terms in mind, since extracting zip folders is a native functionality in v1.1.34:
- `Zip`
- `Extract a zip file`
- `Unzip`

Which will redirect to the FileCopyDir page to the note of the functionality. There's probably few more terms that could fit to the same results, but you get the idea. Thanks!

**Comment by Ragnar-F** [comment]
Well, basically the search can be used for such things. Personally, I use the index only to quickly open pages of commands, functions, etc. by name. So I am rather unwilling to implement your suggestions.

**Comment by Animan8000** [comment]
Sometimes it can be a bit difficult to know what a command or function was called, so I found these search terms sometimes helpful in the documentation, to find easier what you're looking for. Since this is rather new functionality as of a few months ago, I found they might be worth having these terms as searchable results.
