### ISSUE TITLE
v2 #MaxMem removal

### ISSUE THREAD

**Issue by Animan8000** [Lexikos/AutoHotkey_L-Docs#581]
With the removal of [**#MaxMem**](https://www.autohotkey.com/docs/commands/_MaxMem.htm) directive in v2, there isn't a mention what the capacity limits of variables are (if any). It would be nice if it was mentioned in the [**Changes from v1.1 to v2.0**](https://lexikos.github.io/v2/docs/AutoHotkey.htm) page what the default limit now is or if there's no capacity limit at all, just so the user is aware in advance.

**Comment by Ragnar-F** [comment]
I assume that the var capacity is now unlimited resp. is now only limited by system resources. @Lexikos will know more about this.

**Comment by HelgeffegleH** [comment]
that is correct @Ragnar-F.

**Comment by Lexikos** [comment]
That is sufficient.

For a new user, there is no reason to think that there would be a limit. The v1 docs specify the limit under "Variable Capacity and Memory". This section still exists in the v2 docs but does not specify a limit, therefore it can be assumed there isn't one.
