### ISSUE TITLE
v1: suggest add `Out` of WinGetActiveStats & WinGetPos param sign 

### ISSUE THREAD

**Issue by CoffeeChaton** [Lexikos/AutoHotkey_L-Docs#588]
[WinGetActiveStats](https://www.autohotkey.com/docs/commands/WinGetActiveStats.htm)
`WinGetActiveStats, Title, Width, Height, X, Y`
`WinGetActiveStats, OutTitle, OutWidth, OutHeight, OutX, OutY`

[WinGetPos](https://www.autohotkey.com/docs/commands/WinGetPos.htm)
`WinGetPos , X, Y, Width, Height, WinTitle, WinText, ExcludeTitle, ExcludeText`
`WinGetPos , OutX, OutY, OutWidth, OutHeight, , WinTitle, WinText, ExcludeTitle, ExcludeText`

keep OutputVar and InputVar param sign different, suggest to use like `Out` or `Output` prefix.

- FileGetTime, OutputVar 
- FileGetShortcut, LinkFile , OutTarget, OutDir, OutArgs, OutDescription, OutIcon, OutIconNum, OutRunState
- ImageSearch, OutputVarX, OutputVarY
- MouseGetPos , OutputVarX, OutputVarY, OutputVarWin, OutputVarControl
- PixelSearch, OutputVarX, OutputVarY
- Run, Target , WorkingDir, Options, OutputVarPID
- RunWait, Target , WorkingDir, Options, OutputVarPID
- SplitPath, InputVar , OutFileName, OutDir, OutExtension, OutNameNoExt, OutDrive
...etc

**Comment by Ragnar-F** [comment]
Thanks for reporting.

**Comment by CoffeeChaton** [comment]
also
[ControlGetPos ](https://www.autohotkey.com/docs/commands/ControlGetPos.htm)
`ControlGetPos , X, Y, Width, Height, Control, WinTitle, WinText, ExcludeTitle, ExcludeText`
`ControlGetPos , OutX, OutY, OutWidth, OutHeight, Control, WinTitle, WinText, ExcludeTitle, ExcludeText`
