### ISSUE TITLE
Add "target button" and more

### ISSUE THREAD

**Issue by TestDmitriy** [Lexikos/AutoHotkey_L-Docs#592]
Add "target button" please
I have Corsair M65 Pro + M65 RGB + NIGHTSWORD RGB mouses. Would be great to adjust all additional buttons.
iCue is great but too heavy ( more than 1.5Gb) with tones of never used functionality.
Thank you

**Comment by joedf** [comment]
It might already accessible under a different name: `XButton1` or `XButton2`.
Otherwise, you'll likely need to figure what key it is:
https://www.autohotkey.com/docs/KeyList.htm#SpecialKeys
