### ISSUE TITLE
AHK remap vs. registry remap

### ISSUE THREAD

**Issue by trudnorx** [Lexikos/AutoHotkey_L-Docs#600]
The documentation says:
`Registry remapping is generally more pure and effective than [AutoHotkey's remapping](https://www.autohotkey.com/docs/misc/Remap.htm#Remap). For example, it works in a broader variety of games`

This can be misleading. Some games scan keys in a way that bypasses the registry's scancode map, leading to this remapping method having no effect, while AHK successfully remaps the key. I am not sure whether it would even be true that '[registry remapping] works in a broader variety of games'. But even if this is true, the docs could note that in some cases it can be the opposite.

**Comment by Lexikos** [comment]
> This can be misleading.

I think not. "Generally" literally means "in most cases; usually". "A broader variety" doesn't mean every single game.

> Some games scan keys in a way that bypasses the registry's scancode map, leading to this remapping method having no effect, while AHK successfully remaps the key. 

I would like to hear details of any such method of scanning keys.

> But even if this is true, the docs could note that in some cases it can be the opposite.

Anyone is welcome to submit a pull request, but personally I see no need. Surely one would need to try it to know whether it works better or at all for a certain game, and then would know either way.
