### ISSUE TITLE
Send page not displaying correctly when searching for it

### ISSUE THREAD

**Issue by Animan8000** [Lexikos/AutoHotkey_L-Docs#607]
![Screenshot_20221218_160352](https://user-images.githubusercontent.com/30600651/208305654-ce384081-ef92-4a97-96cb-718af27d38a0.png)

How to reproduce:

- Open the docs in the browser.
- Search for `Send` and click on the first result.

Happens on v1 & v2 docs. Direct links to the pages are working fine, but searching does not.

**Comment by w-e-w** [comment]
lots of other pages are also not working
https://www.autohotkey.com/docs/v1/commands/WinSetTitle.htm
https://www.autohotkey.com/docs/v1/commands/Click.htm
https://www.autohotkey.com/docs/v1/commands/WinMove.htm
a few examples the list goes on

**Comment by Animan8000** [comment]
> lots of other pages are also not working https://www.autohotkey.com/docs/v1/commands/WinSetTitle.htm https://www.autohotkey.com/docs/v1/commands/Click.htm https://www.autohotkey.com/docs/v1/commands/WinMove.htm a few examples the list goes on

Yea, only when searching for it and clicking on it. Direct links always seem to be working fine however.
