### ISSUE TITLE
Documentation error (or AHK bug) with `#Requires`

### ISSUE THREAD

**Issue by anonymous1184** [Lexikos/AutoHotkey_L-Docs#615]
In the second example of the `#Requires` directive (the one that uses operators for comparison) reads:

[`#Requires` v1.1](https://www.autohotkey.com/docs/v1/lib/_Requires.htm#Examples)
```ahk
#Requires AutoHotkey >=1.1.36 <1.2
```

[`#Requires` v2](https://www.autohotkey.com/docs/v2/lib/_Requires.htm#Examples)
```ahk
#Requires AutoHotkey >=2.0- <2.1
```

But they won't work. This will show the version selector from UX\launcher.ahk:

```ahk
#Requires AutoHotkey >=1.1.36 <1.2
MsgBox
```

This will:

```ahk
#Requires AutoHotkey >=v1.1.36 <1.2
MsgBox
```

So I don't know if it is a:

- Bug in the code: docs are fine, the interpreter expects only `[\d\.]+`.
- Issue with documentation: example is missing the letter `v`, interpreter is fine.

**Comment by white-gthb** [comment]
Confirmed. The explanation of **Requirement** says it is optional, but that doesn't seem to work for > and >=.  It does seem to work for < and <=

> [v1.1.36+]: One of <, <=, >, >= or = immediately followed by an optional letter "v" and a version number.

**Comment by white-gthb** [comment]
I think the commands work and the documentation is correct. Try without UX\launcher.ahk.

UX\launcher.ahk isn't that smart, causing the confusion.

**Comment by anonymous1184** [comment]
Just tested directly with the interpreters, and the directives work with and without the `v` in the version string.

Turns out is not any of the options I laid out, is a third one: the launcher script :P

**Comment by white-gthb** [comment]
@anonymous1184
You may want to close this issue and open an issue in the [AutoHotkeyUX](https://github.com/AutoHotkey/AutoHotkeyUX) repository.

**Comment by white-gthb** [comment]
I've opened a thread on the AutoHotkey forum:
https://www.autohotkey.com/boards/viewtopic.php?f=14&t=112681

Since the issue is not documentation, I think this issue can be closed here.

**Comment by anonymous1184** [comment]
Thanks!, I don't have an account in the forums.
