### ISSUE TITLE
[v1.1] SetFormat: What's the default NumberType mode?

### ISSUE THREAD

**Issue by Animan8000** [Lexikos/AutoHotkey_L-Docs#624]
[**`SetFormat`**](https://www.autohotkey.com/docs/v1/lib/SetFormat.htm) doesn't seem to mention whether it uses the slow or fast mode for integers and floats (default setting I mean). The in-built variables **`A_FormatInteger`**, **`A_FormatFloat`** tell only the `Format` setting, but not the `NumberType`, which made me wonder whether slow or fast mode is used by default. The documentation doesn't seem to mention what mode is used by default it, at least I couldn't find anything about it.

**Comment by Ragnar-F** [comment]
There are several places on this page where you can infer which of the number types is slow or fast. Just search for "slow" or "fast" on this page.

Integer → slow
Float → slow
IntegerFast → fast
FloatFast → fast

**Comment by Animan8000** [comment]
> There are several places on this page where you can infer which of the number types is slow or fast. Just search for "slow" or "fast" on this page.
> 
> Integer → slow Float → slow IntegerFast → fast FloatFast → fast

My question is rather what's used by default? I know that integer and floats have a fast mode and their names, but is it used by default (?), is basically my question.

**Comment by Animan8000** [comment]
After a conversation on another platform and own benchmarking: it seems like fast mode is always being used by default for integers and floats. It might be worth adding a short and simple sentence in the documentation, that tells the reader that by default always the fast modes are being used for math operations.

**Comment by Lexikos** [comment]
"Fast mode" is just a way of changing the formatting while preserving the default caching behaviour.

> If the slow mode "Integer" or "Float" is used anywhere in the script, even if that SetFormat line is never executed, the caching of integers or floating point numbers (respectively) is disabled the moment the script launches.

That implies that if you don't use SetFormat, or if you use SetFormat in fast mode, caching is not disabled. Caching was added in v1.0.48 to improve performance, but for backward-compatibility reasons, it had to be disabled for any scripts that already contained SetFormat.
