### ISSUE TITLE
What does MyGui.Add(ControlType,...) return?

### ISSUE THREAD

**Issue by drposts** [Lexikos/AutoHotkey_L-Docs#634]
What does MyGui.Add(ControlType,...) return?  

It is not documented where is should be in the help file.  
ref: https://www.autohotkey.com/docs/v2/lib/Gui.htm#Add

**Comment by Ragnar-F** [comment]
The first sentence in the Add box is: Adds a control to the GUI window, and returns a [GuiControl object](https://www.autohotkey.com/docs/v2/lib/GuiControl.htm).
