### ISSUE TITLE
Poor accessibility of the AutoHotkey site

### ISSUE THREAD

**Issue by Lexanni** [Lexikos/AutoHotkey_L-Docs#637]
For the past few days I have been experiencing serious problems accessing the site https://www.autohotkey.com. I'm physically located in Europe. The site accessibility test yielded the following results:

![image](https://user-images.githubusercontent.com/25879623/225838917-6b68d03b-d2d2-4f99-a64c-b6859285e82c.png)

**Comment by Ragnar-F** [comment]
I have the same problem here in Germany. Previously, only the initial connection per session to the server took longer. @ttnnkkrr and @joedf, could you please check what's going on?

Related: https://www.autohotkey.com/boards/viewtopic.php?p=512874#p512874

**Comment by Ragnar-F** [comment]
![image](https://user-images.githubusercontent.com/1332321/225865763-fc8150e0-eaab-4ed7-8f8b-8c2a9b31e29d.png)

**Comment by joedf** [comment]
I am not sure, what happened yet. Anyway, I have turned on "under attack mode" on cloudflare. Should help for now.

**Comment by Ragnar-F** [comment]
Yes, it helped. Thanks.
