### ISSUE TITLE
Error with v2 script KeyboardOnScreen.ahk.

### ISSUE THREAD

**Issue by LAPIII** [Lexikos/AutoHotkey_L-Docs#639]
The script [KeyboardOnScreen.ahk](https://github.com/AutoHotkey/AutoHotkeyDocs/blob/v2/docs/scripts/KeyboardOnScreen.ahk) shows an error at line 90: `Error: Parameter #1 of MonitorGetWorkArea requires a Number, but received an empty string.`

**Comment by Ragnar-F** [comment]
Thanks for reporting.
