### ISSUE TITLE
Possible error in doc pages.

### ISSUE THREAD

**Issue by LAPIII** [Lexikos/AutoHotkey_L-Docs#640]
On the page for (Loop)[https://www.autohotkey.com/docs/v2/lib/Loop.htm], Example #2 includes A_Index and when clicked on, it jumps to the top instead of going to (Loop)[https://www.autohotkey.com/docs/v2/Variables.htm#loop] in Variables and Expressions.

**Comment by Ragnar-F** [comment]
Thanks for reporting. The link was not wrong as such, since the loop page contains information about A_Index, but it could have been more specific. I've changed it to "Variables.htm#Index".
