### ISSUE TITLE
[v2] Potential confusing part about Pixelsearch

### ISSUE THREAD

**Issue by Animan8000** [Lexikos/AutoHotkey_L-Docs#651]
I had earlier today a guy who was getting a bit confused about the v2 documentation, because in v1.1 there used to be a slow and fast mode for Pixelsearch, and slow mode was removed for good reasons in v2 (making the fast mode the default) and it's mentioned also in the [Changes from v1.1 to v2.0](https://www.autohotkey.com/docs/v2/v2-changes.htm) page, however, the v2 page of [Pixelsearch](https://www.autohotkey.com/docs/v2/lib/PixelSearch.htm) still mentions this:
> Although color depths as low as 8-bit (256-color) are supported, the fast mode performs much better in 24-bit or 32-bit color.

Which probably could indirectly let a user (that comes from v1.1 but has not read the changes page in-depth necessarily) believe that there still may be two modes and at worst do a mistake like the other person I mentioned did, with inputting quickly a `mode` parameter that obviously doesn't exist in v2 because of this potentially confusing part. Sure, the docs don't list a mode parameter in v2 for Pixelsearch, but user error is always possible if they read things too quickly or not everything in-depth at that moment.

I'm not sure if removing the qoute from above in the docs is a good idea to avoid this confusion, since only one mode is used anyway.

Thanks

**Comment by Ragnar-F** [comment]
Thanks for reporting.
