### ISSUE TITLE
FileSetTime Partial String Output Inconsistencies

### ISSUE THREAD

**Issue by DepthTrawler** [Lexikos/AutoHotkey_L-Docs#661]
While using FileSetTime func and supplying a partial string for the YYYYMMDDHH24MISS (eg: 20040122) output is unexpected.

`FileSetTime(20040122, "C:\Users\" A_UserName "\Downloads\mouse-and-keyboard-icon-5.jpg", "M")`
`MsgBox FileGetTime("C:\Users\" A_UserName "\Downloads\mouse-and-keyboard-icon-5.jpg", "M") ; returns 20040122000000 (expected)`
Documentation states this should output "Sets the modification date (time will be midnight)" but Windows 11 reports the file time as `Wednesday, ‎January ‎21, ‎2004, ‏‎23:00:00`. Other users report unexpected results on Windows 10. Other users with a different locale report **expected** results. Not sure if this is an AutoHotkey issue or a Windows issue? 

OS: Windows 11 Pro v 22h2

**Comment by Ragnar-F** [comment]
This certainly has something to do with how Windows handles Daylight Saving Time (DST).

**Comment by DepthTrawler** [comment]
I will try turning off DST in Windows and syncing time with the server and report if the issue is resolved.

**Comment by DepthTrawler** [comment]
This can be closed, this is 100% a Windows issue, not an AHK or docs issue.
