### ISSUE TITLE
Version in the title of the chm window for v2.1

### ISSUE THREAD

**Issue by safetycar** [Lexikos/AutoHotkey_L-Docs#662]
I've noticed I had a v2.1 help file open but looking at the window title it only said "v2" which was a bit confusing until I understood what was happening. A title change would be appreciated to differentiate it from the others.

**Comment by Lexikos** [comment]
It says "v2", not "v2.0", just as the forums say "v2" and will remain that way even after v2.1 is released. The program itself is supposed to be backward-compatible, and the documentation includes all v2.0 documentation. There should be no need to have both versions of the documentation, and no need to differentiate between them.

**Comment by safetycar** [comment]
I see, possibly I didn't pay proper attention to the version note of what I was reading at the time.
