### ISSUE TITLE
suggestion:"editors with AHK support"

### ISSUE THREAD

**Issue by foolofdestiny** [Lexikos/AutoHotkey_L-Docs#663]
https://kate-editor.org/ made by KDE
https://kate-editor.org/about-kate/

i dont know what exactly the editor needs to be considered 'supported' but kate seems to have AHK built in...

menubar: ( tools>'mode'+'highlighting')>scripts>autohotkey

also it autodetected my .ahk scripts 

bonuses:
- native linux with windows+macos support 
- built in VI mode for vim users ---details about features and incompatabilities--- https://kate-editor.org/kate-vi-mode/
# theres alot more i just persoanlly dont use 

#/* nvim does apparently have support but im not sure/not very versed at setting up the LSP which needs extension and extra configuration.... where as kate is a click in the settings menu. */

gratitude and TY for the AHK

**Comment by joedf** [comment]
Confirmed! officially listed here! :+1: https://kate-editor.org/syntax/

**Comment by joedf** [comment]
Awesome, thank you. Both of you! 😁
