### ISSUE TITLE
[v2] Incomplete sentence and missing period

### ISSUE THREAD

**Issue by Ragnar-F** [Lexikos/AutoHotkey_L-Docs#682]
There are some writing errors caused by https://github.com/AutoHotkey/AutoHotkeyDocs/commit/fc69626882a30ba7011a299e4308d34a9936c6dd. On lines 141 to 142, the first paragraph is incomplete, and the second paragraph seems to be missing a period between "Unicode packets" and "To prevent".

https://github.com/AutoHotkey/AutoHotkeyDocs/blob/fc69626882a30ba7011a299e4308d34a9936c6dd/docs/lib/InputHook.htm#L141-L142

**Comment by Lexikos** [comment]
I think they were aborted attempts at explaining what is explained by the other new paragraphs.
