### ISSUE TITLE
Small inconsistency between v1 and v2 docs I noticed

### ISSUE THREAD

**Issue by Animan8000** [Lexikos/AutoHotkey_L-Docs#689]
![Screenshot_20240327_120814](https://github.com/AutoHotkey/AutoHotkeyDocs/assets/30600651/b2442c93-12af-4602-aa73-19642e74224e)
![Screenshot_20240327_120836](https://github.com/AutoHotkey/AutoHotkeyDocs/assets/30600651/6f3d319c-d7ac-41b2-a28d-8ed9abecaa2f)

In v1 docs after both copyright symbols there's no space, while in v2 there is. Not a big deal, just a minor inconsistency I noticed.

**Comment by Ragnar-F** [comment]
This is most likely a deliberate decision by @Lexikos, so I won't touch it.

The v1 docs will only be changed if it is really important, as the development/maintenance of v1 has now been discontinued entirely.
