### ISSUE TITLE
Alpha docs still contain v1 code

### ISSUE THREAD

**Issue by Banaanae** [Lexikos/AutoHotkey_L-Docs#690]
I haven't looked into to this too far, but v1 code snippets are still present in alpha docs

From the MsgBox help page
> 2.The script is monitoring the WM_HELP message (0x0053). For example: [OnMessage](mk:@MSITStore:C:\Program%20Files\AutoHotkey\v2\AutoHotkey.chm::/docs/lib/OnMessage.htm)(0x0053, "WM_HELP"). When the WM_HELP function is called, it may guide the user by means such as showing another window or message box.

Note the quoted callback in the OnMessage code

**Comment by Ragnar-F** [comment]
Thanks for reporting. Alpha docs? You mean v2 docs. AutoHotkey v2 has been out of alpha status for several years now.
