### ISSUE TITLE
Issue in `A_ScriptName` docs

### ISSUE THREAD

**Issue by Banaanae** [Lexikos/AutoHotkey_L-Docs#692]
`without its path, e.g. MyScript.ahk.`
Should be
`with its path, e.g. MyScript.ahk.`

https://www.autohotkey.com/docs/v2/Variables.htm#ScriptName

**Comment by Ragnar-F** [comment]
No, it shouldn't. `MsgBox A_ScriptName` shows only the file name.

**Comment by Banaanae** [comment]
I realise mistook path with extension, sorry!
