### ISSUE TITLE
Some omissions on page `Language Codes`.

### ISSUE THREAD

**Issue by Promedio** [Lexikos/AutoHotkey_L-Docs#707]
For [Language Codes](https://www.autohotkey.com/docs/v2/misc/Languages.htm), `0x04B0` is often considered to be `Neutral`.

**Comment by Promedio** [comment]
However, it is usually only used like this:
`;@Ahk2Exe-SetLanguage 0x04B0`

**Comment by Ragnar-F** [comment]
I can't find anything about 04B0 in the [official reference](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/70feba9f-294e-491e-b6eb-56532684c37f).

It seems to be a character-set identifier according to [VERSIONINFO resource](https://learn.microsoft.com/en-us/windows/win32/menurc/versioninfo-resource#charsetID), not a language code.
