### ISSUE TITLE
Link to `ahk-mode.el` too?

### ISSUE THREAD

**Issue by sboosali** [Lexikos/AutoHotkey_L-Docs#714]
Add the newer [ahk-mode](https://github.com/punassuming/ahk-mode) along with the older [ahk-org-mode](https://github.com/tinku99/ahk-org-mode) here (the older one is still useful):
https://github.com/AutoHotkey/AutoHotkeyDocs/blob/db60d00aa5e7a4bece2fc7e817a7a37d82e2e008/docs/lib/Edit.htm#L58

**Comment by Ragnar-F** [comment]
The v1 docs will only be changed if it is really important (i.e. basically only fixes), as the development/maintenance of v1 has been discontinued entirely.
